package solution.gdsc.PathPal.domain.client.domain;

public enum CloseStatus {

    NORMAL, GOING_AWAY, PROTOCOL_ERROR, NOT_ACCEPTABLE,
    NO_STATUS_CODE, NO_CLOSE_FRAME, BAD_DATA, POLICY_VIOLATION,
    TOO_BIG_TO_PROCESS, REQUIRED_EXTENSION, SERVER_ERROR,
    SERVICE_RESTARTED, SERVICE_OVERLOAD, TLS_HANDSHAKE_FAILURE, SESSION_NOT_RELIABLE,

    OPEN, UNKNOWN
}
